"""Add post reporting and hiding functionality

Revision ID: 9b0f20ee8852
Revises: e7396f1b4bf1
Create Date: 2026-01-07 01:09:08.477152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b0f20ee8852'
down_revision = 'e7396f1b4bf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('post_id', 'reporter_id', name='uq_post_report_post_reporter')
    )
    op.create_index(op.f('ix_post_reports_post_id'), 'post_reports', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_reports_report_id'), 'post_reports', ['report_id'], unique=False)
    op.create_index(op.f('ix_post_reports_reporter_id'), 'post_reports', ['reporter_id'], unique=False)
    op.alter_column('group_invitations', 'invitation_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='초대 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('group_invitations', 'group_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='초대된 그룹 ID',
               existing_nullable=False)
    op.alter_column('group_invitations', 'inviter_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='초대를 보낸 사용자 ID',
               existing_nullable=False)
    op.alter_column('group_invitations', 'invitee_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='초대를 받은 사용자 ID',
               existing_nullable=False)
    op.alter_column('group_invitations', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='초대 상태: pending(대기), accepted(수락), declined(거절), expired(만료)',
               existing_nullable=False)
    op.alter_column('group_invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='초대 생성 시각',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('group_invitations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='초대 정보 수정 시각',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_group_invitations_group_id', table_name='group_invitations')
    op.drop_index('idx_group_invitations_invitee_id', table_name='group_invitations')
    op.drop_index('idx_group_invitations_invitee_status', table_name='group_invitations')
    op.drop_index('idx_group_invitations_inviter_id', table_name='group_invitations')
    op.drop_index('idx_group_invitations_status', table_name='group_invitations')
    op.drop_index('idx_group_invitations_unique_pending', table_name='group_invitations', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_table_comment(
        'group_invitations',
        existing_comment='그룹 초대 정보를 저장하는 테이블',
        schema=None
    )
    op.create_index(op.f('ix_notifications_comment_id'), 'notifications', ['comment_id'], unique=False)
    op.create_index(op.f('ix_notifications_post_id'), 'notifications', ['post_id'], unique=False)
    op.add_column('posts', sa.Column('report_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_posts_is_hidden'), 'posts', ['is_hidden'], unique=False)
    op.alter_column('users', 'selected_achievement_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='사용자가 선택한 대표 칭호 ID. 획득한 칭호 중 하나를 선택할 수 있음.',
               existing_nullable=True)
    op.drop_index('idx_users_selected_achievement_id', table_name='users')
    op.drop_index('idx_users_unique_code', table_name='users')
    op.drop_constraint('uq_users_unique_code', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_unique_code', 'users', ['unique_code'])
    op.create_index('idx_users_unique_code', 'users', ['unique_code'], unique=False)
    op.create_index('idx_users_selected_achievement_id', 'users', ['selected_achievement_id'], unique=False)
    op.alter_column('users', 'selected_achievement_id',
               existing_type=sa.INTEGER(),
               comment='사용자가 선택한 대표 칭호 ID. 획득한 칭호 중 하나를 선택할 수 있음.',
               existing_nullable=True)
    op.drop_index(op.f('ix_posts_is_hidden'), table_name='posts')
    op.drop_column('posts', 'is_hidden')
    op.drop_column('posts', 'report_count')
    op.drop_index(op.f('ix_notifications_post_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_comment_id'), table_name='notifications')
    op.create_table_comment(
        'group_invitations',
        '그룹 초대 정보를 저장하는 테이블',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_group_invitations_unique_pending', 'group_invitations', ['group_id', 'invitee_id'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.create_index('idx_group_invitations_status', 'group_invitations', ['status'], unique=False)
    op.create_index('idx_group_invitations_inviter_id', 'group_invitations', ['inviter_id'], unique=False)
    op.create_index('idx_group_invitations_invitee_status', 'group_invitations', ['invitee_id', 'status'], unique=False)
    op.create_index('idx_group_invitations_invitee_id', 'group_invitations', ['invitee_id'], unique=False)
    op.create_index('idx_group_invitations_group_id', 'group_invitations', ['group_id'], unique=False)
    op.alter_column('group_invitations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='초대 정보 수정 시각',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('group_invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='초대 생성 시각',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('group_invitations', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='초대 상태: pending(대기), accepted(수락), declined(거절), expired(만료)',
               existing_nullable=False)
    op.alter_column('group_invitations', 'invitee_id',
               existing_type=sa.INTEGER(),
               comment='초대를 받은 사용자 ID',
               existing_nullable=False)
    op.alter_column('group_invitations', 'inviter_id',
               existing_type=sa.INTEGER(),
               comment='초대를 보낸 사용자 ID',
               existing_nullable=False)
    op.alter_column('group_invitations', 'group_id',
               existing_type=sa.INTEGER(),
               comment='초대된 그룹 ID',
               existing_nullable=False)
    op.alter_column('group_invitations', 'invitation_id',
               existing_type=sa.INTEGER(),
               comment='초대 ID (Primary Key)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_post_reports_reporter_id'), table_name='post_reports')
    op.drop_index(op.f('ix_post_reports_report_id'), table_name='post_reports')
    op.drop_index(op.f('ix_post_reports_post_id'), table_name='post_reports')
    op.drop_table('post_reports')
    # ### end Alembic commands ###

