"""Add customer support table

Revision ID: f89aee6c2e9f
Revises: 9b0f20ee8852
Create Date: 2026-01-07 02:11:10.176938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89aee6c2e9f'
down_revision = '9b0f20ee8852'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_support',
    sa.Column('support_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('answer_content', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('support_id')
    )
    op.create_index(op.f('ix_customer_support_status'), 'customer_support', ['status'], unique=False)
    op.create_index(op.f('ix_customer_support_support_id'), 'customer_support', ['support_id'], unique=False)
    op.create_index(op.f('ix_customer_support_type'), 'customer_support', ['type'], unique=False)
    op.create_index(op.f('ix_customer_support_user_id'), 'customer_support', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_support_user_id'), table_name='customer_support')
    op.drop_index(op.f('ix_customer_support_type'), table_name='customer_support')
    op.drop_index(op.f('ix_customer_support_support_id'), table_name='customer_support')
    op.drop_index(op.f('ix_customer_support_status'), table_name='customer_support')
    op.drop_table('customer_support')
    # ### end Alembic commands ###

